# versi API  yang didefinisikan
version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  
jobs:
  build-app-karsajobs-ui:
    executor: docker/docker
    environment:
      IMAGE_NAME: ghcr.io/ihyaksm/karsajobs-ui
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publis Docker Image to Github Container Registry
          # perintah menggunakan secret untuk github
          command: |
            echo "CR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

wordkflows:
  ci:
    # urutuan penugasan
    jobs:
      # menggunakan hadolint
      - docker/hadolint:
          dockerfiles: './Dockerfile'
      # menjalankan test app
      - test-app
      # membuild 
      - build-app-karsajobs-ui:
          requires:
            - docker/hadolint
        